# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
variables:
  CI: "false"

stages:
  - build
  - test
  - package
  - verify
  - deploy
before_script:
  - echo "Setting up Maven build environment..."


#Building
build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21
  script:
    - echo "building application"
    - mvn clean compile


#Testing
test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-21
  dependencies:
    - build #refers to the job and not the stage
  script:
    - echo "running tests"
    - mvn test-compile
    - mvn test #runs unit tests

#Packaging
package:
  stage: package
  image: maven:3.9.9-eclipse-temurin-21
  script:
    - echo "packaging application"
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar

#verifying
verify:
  stage: verify
  image: maven:3.9.9-eclipse-temurin-21
  dependencies:
    - package
  script:
    - echo "veryfying application (style, security, and correctness)"
    - mvn verify

#Deploying
deploy:
  stage: deploy
  image: maven:3.9.9-eclipse-temurin-21
  only:
    - main
  script:
    - echo "Deploying application (Nothing to deploy)"
